language: python
matrix:
  include:
    # - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
install:
  - pip install .[tests,numba]
  - pip install pytest-travis-fold  # for nicer output
script:
  - pip freeze  # since we use the non-versioned dependencies in setup.py
  # run pytest. the bash code makes sure to output a blank line when no output has been received for 5*60=300 seconds
  - "pytest --durations=0 -v --color yes  | tee /dev/tty | while true; do read -t300 ; rv=$?; if [[ $rv > 128 ]] ; then echo -e '\n'; elif [[ $rv > 0 ]] ; then break ; fi ; done"

