language: python
matrix:
  include:
    # - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
install:
  - pip install .[tests,numba]
  - pip install pytest-travis-fold  # for nicer output
script:
  - pip freeze  # log output since we use non-versioned dependencies in setup.py
  - travis_wait  pytest --durations=0 -v

