language: python
dist: xenial  # required for Python >= 3.7 <https://github.com/travis-ci/travis-ci/issues/9069> and PyPy3 >5.8 <https://travis-ci.community/t/add-pypy-7-support/2228/6>

python:
  # - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3"

# dependencies

addons:
  apt:
    update: true
    packages:
      - pypy-dev
      - gfortran-5
      - libatlas-base-dev
      - libatlas-dev
      - liblapack-dev
      - libopenblas-dev
cache: pip
install:
  - |
      if [[ "${TRAVIS_PYTHON_VERSION}" = 'pypy'* ]]; then
        pip install cython "numpy!=1.16.3" # <https://bitbucket.org/pypy/pypy/issues/3008/importerror-numpy-with-pypy36-711>
      else
        pip install .[numexpr]
      fi
  - pip install .[tests]
  - pip install pytest-travis-fold  # for nicer output

# tests

env:
  matrix:
    - SUITE="not check_estimator"  # own tests
    - SUITE="check_estimator"  # only sklearn compatibility testsuite
script:
  - pip freeze  # since we use the non-pinned dependencies in setup.py, log which versions we got
  - 'pytest --durations=0 -v --color yes -k "$SUITE"'
